---
title: LeetCode Database Notes (42 Problems)
author: Qiū Ruì
date: '2019-04-22'
slug: leetcode-database-notes-42-problems
categories: []
tags:
  - SQL
  - LeetCode
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
meta_img: image/image.png
description: Description for the page.
---

***Updated on 2019-04-26.***


✅ #175
✅ #176
✅ #177
✅ #178
✅ #180
✅ #181
✅ #182
✅ #183
✅ #184
✅ #185
✅ #196
✅ #197
✅ #262
❌ #569
❌ #570
❌ #571
❌ #574
❌ #577
❌ #578
❌ #579
❌ #580
❌ #584
❌ #585
❌ #586
✅ #595
✅ #596
❌ #597
✅ #601
❌ #602
❌ #603
❌ #607
❌ #608
❌ #610
❌ #612
❌ #613
❌ #614
❌ #615
❌ #618
❌ #619
✅ #620
✅ #626
✅ #627

## 175. Combine Two Tables

Table: `Person`

<pre><output>
+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| PersonId    | int     |
| FirstName   | varchar |
| LastName    | varchar |
+-------------+---------+
</output></pre>

`PersonId` is the primary key column for this table.

Table: `Address`

<pre>
+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| AddressId   | int     |
| PersonId    | int     |
| City        | varchar |
| State       | varchar |
+-------------+---------+
</pre>

`AddressId` is the primary key column for this table.

Write a SQL query for a report that provides the following information for each person in the Person table, regardless if there is an address for each of those people:

    FirstName, LastName, City, State

### Solution

```mysql
SELECT FirstName, LastName, City, State
FROM Person 
LEFT JOIN Address ON Person.PersonId = Address.PersonId;
```

Note: There is no `FULL JOIN` in MySQL.

## 176. Second Highest Salary

Write a SQL query to get the second highest salary from the `Employee` table.

<pre>
+----+--------+
| Id | Salary |
+----+--------+
| 1  | 100    |
| 2  | 200    |
| 3  | 300    |
+----+--------+
</pre>

For example, given the above Employee table, the query should return `200` as the second highest salary. If there is no second highest salary, then the query should return `null`.

<pre>
+---------------------+
| SecondHighestSalary |
+---------------------+
| 200                 |
+---------------------+
</pre>

### Solution

```MySQL
SELECT MAX(Salary) as SecondHighestSalary
FROM Employee
WHERE Salary < (SELECT MAX(Salary) FROM Employee);
```

## 177. Nth Highest Salary

Write a SQL query to get the nth highest salary from the `Employee` table.

<pre>
+----+--------+
| Id | Salary |
+----+--------+
| 1  | 100    |
| 2  | 200    |
| 3  | 300    |
+----+--------+
</pre>

For example, given the above Employee table, the nth highest salary where n = 2 is `200`. If there is no nth highest salary, then the query should return `null`.

<pre>
+------------------------+
| getNthHighestSalary(2) |
+------------------------+
| 200                    |
+------------------------+
</pre>

### Solution

```mysql
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  SET N = N-1;
  RETURN (
      SELECT DISTINCT Salary FROM Employee ORDER BY Salary DESC LIMIT 1 OFFSET N 
  );
END
```

The idea is to use `LIMIT` and `OFFSET` in MySQL to skip those first `N-1` higher salaries than the nth one you really need to pick out.

## 178. Rank Scores

Write a SQL query to rank scores. If there is a tie between two scores, both should have the same ranking. Note that after a tie, the next ranking number should be the next consecutive integer value. In other words, there should be no "holes" between ranks.

<pre>
+----+-------+
| Id | Score |
+----+-------+
| 1  | 3.50  |
| 2  | 3.65  |
| 3  | 4.00  |
| 4  | 3.85  |
| 5  | 4.00  |
| 6  | 3.65  |
+----+-------+
</pre>

For example, given the above `Scores` table, your query should generate the following report (order by highest score):

<pre>
+-------+------+
| Score | Rank |
+-------+------+
| 4.00  | 1    |
| 4.00  | 1    |
| 3.85  | 2    |
| 3.65  | 3    |
| 3.65  | 3    |
| 3.50  | 4    |
+-------+------+
</pre>

### Solution

```mysql
SELECT s.Score, COUNT(t.Score) as Rank FROM
(SELECT DISTINCT Score from Scores) AS t, Scores as s
WHERE s.Score <= t.Score
GROUP BY s.Id, s.Score
ORDER BY s.Score DESC;
```

The idea here is to use two `Scores` tables side-by-side, one used to keep track of scores, and one used to calculate the rank of them. Note that the rank is decided by **how many other distinct scores you are higher than.** After that, all you need to do is to group them by `Id` and `Score`, then order the scores by descending order.

## 180. Consecutive Numbers

Write a SQL query to find all numbers that appear at least three times consecutively.

<pre>
+----+-----+
| Id | Num |
+----+-----+
| 1  |  1  |
| 2  |  1  |
| 3  |  1  |
| 4  |  2  |
| 5  |  1  |
| 6  |  2  |
| 7  |  2  |
+----+-----+
</pre>

For example, given the above `Logs` table, `1` is the only number that appears consecutively for at least three times.

<pre>
+-----------------+
| ConsecutiveNums |
+-----------------+
| 1               |
+-----------------+
</pre>

### Solution

```mysql
SELECT DISTINCT
    l1.Num AS ConsecutiveNums
FROM
    Logs l1,
    Logs l2,
    Logs l3
WHERE
    l1.Id = l2.Id - 1
    AND l2.Id = l3.Id - 1
    AND l1.Num = l2.Num
    AND l2.Num = l3.Num
;
```

Just keep in your mind that what constitutes a record of 3 consecutive numbers?

1. Consecutive `Id`s.
2. The same `Num`.

## 181. Employees Earning More Than Their Managers

The `Employee` table holds all employees including their managers. Every employee has an Id, and there is also a column for the manager Id.

<pre>
+----+-------+--------+-----------+
| Id | Name  | Salary | ManagerId |
+----+-------+--------+-----------+
| 1  | Joe   | 70000  | 3         |
| 2  | Henry | 80000  | 4         |
| 3  | Sam   | 60000  | NULL      |
| 4  | Max   | 90000  | NULL      |
+----+-------+--------+-----------+
</pre>

Given the `Employee` table, write a SQL query that finds out employees who earn more than their managers. For the above table, Joe is the only employee who earns more than his manager.

<pre>
+----------+
| Employee |
+----------+
| Joe      |
+----------+
</pre>

### Solution

```mysql
SELECT e1.Name as Employee
FROM Employee as e1
JOIN Employee as e2 on e1.ManagerId = e2.Id
WHERE e1.Salary > e2.Salary;
```

## 182. Duplicate Emails

Write a SQL query to find all duplicate emails in a table named `Person`.

<pre>
+----+---------+
| Id | Email   |
+----+---------+
| 1  | a@b.com |
| 2  | c@d.com |
| 3  | a@b.com |
+----+---------+
</pre>

For example, your query should return the following for the above table:

<pre>
+---------+
| Email   |
+---------+
| a@b.com |
+---------+
</pre>

### Solution

```mysql
SELECT Email
FROM Person
GROUP BY EMAIL
HAVING COUNT(*)>1;
```

## 183. Customers Who Never Order

Suppose that a website contains two tables, the `Customers` table and the `Orders` table. Write a SQL query to find all customers who never order anything.

Table: `Customers`.

<pre>
+----+-------+
| Id | Name  |
+----+-------+
| 1  | Joe   |
| 2  | Henry |
| 3  | Sam   |
| 4  | Max   |
+----+-------+
</pre>

Table: `Orders`.

<pre>
+----+------------+
| Id | CustomerId |
+----+------------+
| 1  | 3          |
| 2  | 1          |
+----+------------+
</pre>

Using the above tables as example, return the following:

<pre>
+-----------+
| Customers |
+-----------+
| Henry     |
| Max       |
+-----------+
</pre>

### Solution

```mysql
SELECT Name AS Customers
FROM Customers
LEFT JOIN Orders
ON Customers.Id = Orders.CustomerId
WHERE Orders.Id IS NULL;
```

## 184. Department Highest Salary

The `Employee` table holds all employees. Every employee has an Id, a salary, and there is also a column for the department Id.

<pre>
+----+-------+--------+--------------+
| Id | Name  | Salary | DepartmentId |
+----+-------+--------+--------------+
| 1  | Joe   | 70000  | 1            |
| 2  | Jim   | 90000  | 1            |
| 3  | Henry | 80000  | 2            |
| 4  | Sam   | 60000  | 2            |
| 5  | Max   | 90000  | 1            |
+----+-------+--------+--------------+
</pre>

The `Department` table holds all departments of the company.

<pre>
+----+----------+
| Id | Name     |
+----+----------+
| 1  | IT       |
| 2  | Sales    |
+----+----------+
</pre>

Write a SQL query to find employees who have the highest salary in each of the departments. For the above tables, your SQL query should return the following rows (order of rows does not matter).

<pre>
+------------+----------+--------+
| Department | Employee | Salary |
+------------+----------+--------+
| IT         | Max      | 90000  |
| IT         | Jim      | 90000  |
| Sales      | Henry    | 80000  |
+------------+----------+--------+
</pre>

Explanation:

Max and Jim both have the highest salary in the IT department and Henry has the highest salary in the Sales department.

### Solution

```mysql
# inner join without a join
SELECT Department.Name as Department, Employee.Name as Employee, Employee.Salary
FROM Employee, Department
WHERE Employee.DepartmentId = Department.Id
    AND Employee.Salary = (
        SELECT MAX(Salary) FROM Employee AS temp WHERE temp.DepartmentId=Employee.DepartmentId
    );
```

## 185. Department Top Three Salaries

The `Employee` table holds all employees. Every employee has an Id, and there is also a column for the department Id.

+----+-------+--------+--------------+
| Id | Name  | Salary | DepartmentId |
+----+-------+--------+--------------+
| 1  | Joe   | 85000  | 1            |
| 2  | Henry | 80000  | 2            |
| 3  | Sam   | 60000  | 2            |
| 4  | Max   | 90000  | 1            |
| 5  | Janet | 69000  | 1            |
| 6  | Randy | 85000  | 1            |
| 7  | Will  | 70000  | 1            |
+----+-------+--------+--------------+

The `Department` table holds all departments of the company.

+----+----------+
| Id | Name     |
+----+----------+
| 1  | IT       |
| 2  | Sales    |
+----+----------+

Write a SQL query to find employees who earn the top three salaries in each of the department. For the above tables, your SQL query should return the following rows (order of rows does not matter).

<pre>
+------------+----------+--------+
| Department | Employee | Salary |
+------------+----------+--------+
| IT         | Max      | 90000  |
| IT         | Randy    | 85000  |
| IT         | Joe      | 85000  |
| IT         | Will     | 70000  |
| Sales      | Henry    | 80000  |
| Sales      | Sam      | 60000  |
+------------+----------+--------+
</pre>

Explanation:

In IT department, Max earns the highest salary, both Randy and Joe earn the second highest salary, and Will earns the third highest salary. There are only two employees in the Sales department, Henry earns the highest salary while Sam earns the second highest salary.

### Solution

**Note:** Top 3 highest (without order) means there are less than 3 people having higher salaries than him or her.

```mysql
SELECT
    d.Name AS 'Department', e1.Name AS 'Employee', e1.Salary
FROM
    Employee e1
        JOIN
    Department d ON e1.DepartmentId = d.Id
WHERE
    3 > (SELECT
            COUNT(DISTINCT e2.Salary)
         FROM
            Employee e2
         WHERE
            e2.Salary > e1.Salary
                AND e1.DepartmentId = e2.DepartmentID
        )
;
```

## 196. Delete Duplicate Emails

Write a SQL query to delete all duplicate email entries in a table named `Person`, keeping only unique emails based on its smallest `Id`.

<pre>
+----+------------------+
| Id | Email            |
+----+------------------+
| 1  | john@example.com |
| 2  | bob@example.com  |
| 3  | john@example.com |
+----+------------------+
</pre>

`Id` is the primary key column for this table.

For example, after running your query, the above `Person` table should have the following rows:

<pre>
+----+------------------+
| Id | Email            |
+----+------------------+
| 1  | john@example.com |
| 2  | bob@example.com  |
+----+------------------+
</pre>

**Note:** Your output is the whole `Person` table after executing your sql. Use `delete` statement.

### Solution

```mysql
DELETE p1 FROM Person AS p1
JOIN Person AS p2 ON p1.Email=p2.Email AND p1.Id>p2.Id;
```

## 197. Rising Temperature

Given a `Weather` table, write a SQL query to find all dates' Ids with higher temperature compared to its previous (yesterday's) dates.

<pre>
+---------+------------------+------------------+
| Id(INT) | RecordDate(DATE) | Temperature(INT) |
+---------+------------------+------------------+
|       1 |       2015-01-01 |               10 |
|       2 |       2015-01-02 |               25 |
|       3 |       2015-01-03 |               20 |
|       4 |       2015-01-04 |               30 |
+---------+------------------+------------------+
</pre>

For example, return the following Ids for the above `Weather` table:

<pre>
+----+
| Id |
+----+
|  2 |
|  4 |
+----+
</pre>


### Solution

```mysql
SELECT w1.Id
FROM Weather AS w1, Weather AS w2
WHERE DATEDIFF(w1.RecordDate,w2.RecordDate)=1 AND w1.Temperature>w2.Temperature;
```

**Note:** I first tried with `w1.RecordDate=w2.RecordDate+1`. It worked with some test cases, but failed in some. Seems that I need to take a look at datetime arithmetic in SQL later.

## 262. Trips and Users

The `Trips` table holds all taxi trips. Each trip has a unique Id, while Client_Id and Driver_Id are both foreign keys to the `Users_Id` at the Users table. Status is an ENUM type of (‘completed’, ‘cancelled_by_driver’, ‘cancelled_by_client’).

<pre>
+----+-----------+-----------+---------+--------------------+----------+
| Id | Client_Id | Driver_Id | City_Id |        Status      |Request_at|
+----+-----------+-----------+---------+--------------------+----------+
| 1  |     1     |    10     |    1    |     completed      |2013-10-01|
| 2  |     2     |    11     |    1    | cancelled_by_driver|2013-10-01|
| 3  |     3     |    12     |    6    |     completed      |2013-10-01|
| 4  |     4     |    13     |    6    | cancelled_by_client|2013-10-01|
| 5  |     1     |    10     |    1    |     completed      |2013-10-02|
| 6  |     2     |    11     |    6    |     completed      |2013-10-02|
| 7  |     3     |    12     |    6    |     completed      |2013-10-02|
| 8  |     2     |    12     |    12   |     completed      |2013-10-03|
| 9  |     3     |    10     |    12   |     completed      |2013-10-03| 
| 10 |     4     |    13     |    12   | cancelled_by_driver|2013-10-03|
+----+-----------+-----------+---------+--------------------+----------+
</pre>

The `Users` table holds all users. Each user has an unique Users_Id, and Role is an ENUM type of (‘client’, ‘driver’, ‘partner’).

<pre>
+----------+--------+--------+
| Users_Id | Banned |  Role  |
+----------+--------+--------+
|    1     |   No   | client |
|    2     |   Yes  | client |
|    3     |   No   | client |
|    4     |   No   | client |
|    10    |   No   | driver |
|    11    |   No   | driver |
|    12    |   No   | driver |
|    13    |   No   | driver |
+----------+--------+--------+
</pre>

Write a SQL query to find the cancellation rate of requests made by unbanned users between **Oct 1, 2013** and **Oct 3, 2013**. For the above tables, your SQL query should return the following rows with the cancellation rate being rounded to two decimal places.

<pre>
+------------+-------------------+
|     Day    | Cancellation Rate |
+------------+-------------------+
| 2013-10-01 |       0.33        |
| 2013-10-02 |       0.00        |
| 2013-10-03 |       0.50        |
+------------+-------------------+
</pre>

### Solution

```mysql
SELECT
    Trips.Request_at As Day,
    round(sum(if(status != 'completed', 1, 0)) / sum(1), 2) AS 'Cancellation Rate' 
FROM
    Trips 
JOIN
    Users ON Trips.Client_Id = Users.Users_Id
WHERE
    Users.Banned = "No"
    AND Trips.Request_at BETWEEN "2013-10-01" AND "2013-10-03"
GROUP BY
    Day;
```

## 569. Median Employee Salary

## 570. Managers with at Least 5 Direct Reports

## 571. Find Median Given Frequency of Numbers

## 574. Winning Candidates

## 577. Employee Bonus

## 578. Get Highest Answer Rate Question

## 579. Find Cumulative Salary of an Employee

## 580. Count Student Number in Departments

## 584. Find Customer Referee

## 585. Investments in 2016

## 586. Customer Placing the Largest Number of Orders

## 595. Big Countries

There is a table `World`

<pre>
+-----------------+------------+------------+--------------+---------------+
| name            | continent  | area       | population   | gdp           |
+-----------------+------------+------------+--------------+---------------+
| Afghanistan     | Asia       | 652230     | 25500100     | 20343000      |
| Albania         | Europe     | 28748      | 2831741      | 12960000      |
| Algeria         | Africa     | 2381741    | 37100000     | 188681000     |
| Andorra         | Europe     | 468        | 78115        | 3712000       |
| Angola          | Africa     | 1246700    | 20609294     | 100990000     |
+-----------------+------------+------------+--------------+---------------+
</pre>

A country is big if it has an area of bigger than 3 million square km or a population of more than 25 million.

Write a SQL solution to output big countries' name, population and area.

For example, according to the above table, we should output:

<pre>
+--------------+-------------+--------------+
| name         | population  | area         |
+--------------+-------------+--------------+
| Afghanistan  | 25500100    | 652230       |
| Algeria      | 37100000    | 2381741      |
+--------------+-------------+--------------+
</pre>

### Solution

```mysql
select name, population, area
from World
where area > 3000000 or population > 25000000;
```

## 596. Classes More Than 5 Students

There is a table `courses` with columns: **student** and **class**

Please list out all classes which have more than or equal to 5 students.

For example, the table:

<pre>
+---------+------------+
| student | class      |
+---------+------------+
| A       | Math       |
| B       | English    |
| C       | Math       |
| D       | Biology    |
| E       | Math       |
| F       | Computer   |
| G       | Math       |
| H       | Math       |
| I       | Math       |
+---------+------------+
</pre>

Should output:

<pre>
+---------+
| class   |
+---------+
| Math    |
+---------+
</pre>

**Note:** The students should not be counted duplicate in each course.

### Solution

```mysql
select class
from (select
      class, count(DISTINCT student) as num
      from
      courses
      group by class) as temp_table
where num >= 5;
```

## 597. Friend Requests I: Overall Acceptance Rate

## 601. Human Trafic of Stadium

X city built a new stadium, each day many people visit it and the stats are saved as these columns: **id, visit_date, people**

Please write a query to display the records which have 3 or more consecutive rows and the amount of people more than 100(inclusive).

For example, the table `stadium`: 

<pre>
+------+------------+-----------+
| id   | visit_date | people    |
+------+------------+-----------+
| 1    | 2017-01-01 | 10        |
| 2    | 2017-01-02 | 109       |
| 3    | 2017-01-03 | 150       |
| 4    | 2017-01-04 | 99        |
| 5    | 2017-01-05 | 145       |
| 6    | 2017-01-06 | 1455      |
| 7    | 2017-01-07 | 199       |
| 8    | 2017-01-08 | 188       |
+------+------------+-----------+
</pre>

For the sample data above, the output is:

<pre>
+------+------------+-----------+
| id   | visit_date | people    |
+------+------------+-----------+
| 5    | 2017-01-05 | 145       |
| 6    | 2017-01-06 | 1455      |
| 7    | 2017-01-07 | 199       |
| 8    | 2017-01-08 | 188       |
+------+------------+-----------+
</pre>

**Note:** Each day only have one row record, and the dates are increasing with id increasing.

### Solution

```mysql
select distinct t1.*
from stadium t1, stadium t2, stadium t3
where t1.people>=100 and t2.people>=100 and t3.people>=100 and
(
(t1.id-t2.id=1 and t1.id-t3.id=2 and t2.id-t3.id=1)
or
(t2.id-t1.id=1 and t2.id-t3.id=2 and t1.id-t3.id=1)
or
(t3.id-t2.id=1 and t2.id-t1.id=1 and t3.id-t1.id=2)
)
order by t1.id;
```

## 602. Friend Requests II: Who Has the Most Friends

## 603. Consecutive Available Seats

## 607. Sales Person

## 608. Tree Node

## 610. Triangle Judgement

## 612. Shortest Distance in a Plane

## 613. Shortest Distance in a Line

## 614. Second Degree Follower

## 615. Average Salary: Departments VS Company

## 618. Students Report By Geography

## 619. Biggest Single Number

## 620. Not Boring Movies

X city opened a new cinema, many people would like to go to this cinema. The cinema also gives out a poster indicating the movies’ ratings and descriptions.

Please write a SQL query to output movies with an odd numbered ID and a description that is not 'boring'. Order the result by rating.

For example, table `cinema`:

<pre>
+---------+-----------+--------------+-----------+
|   id    | movie     |  description |  rating   |
+---------+-----------+--------------+-----------+
|   1     | War       |   great 3D   |   8.9     |
|   2     | Science   |   fiction    |   8.5     |
|   3     | irish     |   boring     |   6.2     |
|   4     | Ice song  |   Fantacy    |   8.6     |
|   5     | House card|   Interesting|   9.1     |
+---------+-----------+--------------+-----------+
</pre>

For the example above, the output should be: 

<pre>
+---------+-----------+--------------+-----------+
|   id    | movie     |  description |  rating   |
+---------+-----------+--------------+-----------+
|   5     | House card|   Interesting|   9.1     |
|   1     | War       |   great 3D   |   8.9     |
+---------+-----------+--------------+-----------+
</pre>

### Solution

```mysql
select *
from cinema
where description != "boring" and id % 2 = 1
order by rating desc;
```

## 626. Exchange Seats

Mary is a teacher in a middle school and she has a table `seat` storing students' names and their corresponding seat ids.
The column **id** is continuous increment.

Mary wants to change seats for the adjacent students.

Can you write a SQL query to output the result for Mary?

<pre>
+---------+---------+
|    id   | student |
+---------+---------+
|    1    | Abbot   |
|    2    | Doris   |
|    3    | Emerson |
|    4    | Green   |
|    5    | Jeames  |
+---------+---------+
</pre>

For the sample input, the output is: 

<pre>
+---------+---------+
|    id   | student |
+---------+---------+
|    1    | Doris   |
|    2    | Abbot   |
|    3    | Green   |
|    4    | Emerson |
|    5    | Jeames  |
+---------+---------+
</pre>

**Note:** If the number of students is odd, there is no need to change the last one's seat.

### Solution

```mysql
SELECT
    (CASE
        WHEN id%2!= 0 AND counts != id THEN id + 1
        WHEN id%2!= 0 AND counts = id THEN id
        ELSE id - 1
    END) AS id,
    student
FROM
    seat,
    (SELECT
        COUNT(*) AS counts
    FROM
        seat) AS seat_counts
ORDER BY id ASC;
```

## 627. Swap Salary

Given a table `salary`, such as the one below, that has m=male and f=female values. Swap all f and m values (i.e., change all f values to m and vice versa) with a **single update statement** and no intermediate temp table.

Note that you must write a single update statement, **DO NOT** write any select statement for this problem.

**Example:**

<pre>
| id | name | sex | salary |
|----|------|-----|--------|
| 1  | A    | m   | 2500   |
| 2  | B    | f   | 1500   |
| 3  | C    | m   | 5500   |
| 4  | D    | f   | 500    |
</pre>

After running your update statement, the above salary table should have the following rows:

<pre>
| id | name | sex | salary |
|----|------|-----|--------|
| 1  | A    | f   | 2500   |
| 2  | B    | m   | 1500   |
| 3  | C    | f   | 5500   |
| 4  | D    | m   | 500    |
</pre>

### Solution

```mysql
update salary
set sex = case when sex = "f" then "m"
               when sex = "m" then "f"
               end
```

***

I also practiced adding table of contents in a blogdown post by setting the `output` parameter.

As Yihui mentions in this [pull request](https://github.com/yihui/hugo-xmin/pull/7), all you need to do is add this in YAML:

```yaml
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
```

`toc_depth: 2` means it will show up to 2 levels of headers.


